apiVersion: apps/v1
kind: Deployment
metadata:
  name: wine-model
  labels:
    app: wine-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wine-model
  template:
    metadata:
      labels:
        app: wine-model
    spec:
      containers:
      - name: wine-model
        image: mahderam/wine-model:v1
        imagePullPolicy: IfNotPresent
        imagePullSecrets:
          - name: myregistrykey
    ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 15
